using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Unity.Localization.Roslyn;

[Generator]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Features.Localization";
    private const string ClassName = "Loc";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        // Separate SharedData and StringTable files
        var sharedDataFiles = new List<AdditionalText>();
        var stringTableFiles = new List<AdditionalText>();

        foreach (var file in files)
        {
            var fileName = System.IO.Path.GetFileName(file.Path);
            if (fileName.EndsWith("SharedData.asset", StringComparison.OrdinalIgnoreCase))
                sharedDataFiles.Add(file);
            else if (fileName.EndsWith("_en.asset", StringComparison.OrdinalIgnoreCase))
                stringTableFiles.Add(file);
        }

        // Parse all SharedData files, index by GUID
        var sharedDataByGuid = new Dictionary<string, SharedTableData>(StringComparer.OrdinalIgnoreCase);
        foreach (var sharedFile in sharedDataFiles)
        {
            try
            {
                var sharedData = LocalizationAssetParser.ParseSharedData(sharedFile, context.CancellationToken);
                if (!string.IsNullOrEmpty(sharedData.Guid))
                    sharedDataByGuid[sharedData.Guid] = sharedData;
            }
            catch (Exception exception)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "LOCGEN001", "Shared data parse error",
                        "Failed to parse SharedData '{0}': {1}",
                        "SourceGenerator", DiagnosticSeverity.Warning, true),
                    Location.None, sharedFile.Path, exception.Message));
            }
        }

        // Parse each StringTable file, pair with SharedData via GUID
        var tableInfos = new List<TableInfo>();
        foreach (var tableFile in stringTableFiles)
        {
            try
            {
                var text = tableFile.GetText(context.CancellationToken)?.ToString();
                if (text is null) continue;

                // Extract the GUID from the StringTable to find its SharedData
                var guidMatch = System.Text.RegularExpressions.Regex.Match(
                    text, @"m_SharedData:.*guid:\s*([a-f0-9]+)");
                if (!guidMatch.Success) continue;

                var guid = guidMatch.Groups[1].Value;
                if (!sharedDataByGuid.TryGetValue(guid, out var sharedData)) continue;

                var tableInfo = LocalizationAssetParser.Parse(text, sharedData);
                tableInfos.Add(tableInfo);
            }
            catch (Exception exception)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "LOCGEN002", "String table parse error",
                        "Failed to parse StringTable '{0}': {1}",
                        "SourceGenerator", DiagnosticSeverity.Warning, true),
                    Location.None, tableFile.Path, exception.Message));
            }
        }

        // Generate one .g.cs per table
        foreach (var tableInfo in tableInfos.OrderBy(table => table.ClassName))
        {
            var source = EmitTableClass(tableInfo);
            context.AddSource($"Loc.{tableInfo.ClassName}.g.cs", source);
        }
    }

    private static string EmitTableClass(TableInfo tableInfo)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine($"namespace {Namespace}");
        builder.AppendLine("{");
        builder.AppendLine($"    public static partial class {ClassName}");
        builder.AppendLine("    {");
        builder.AppendLine($"        public static class {Sanitize(tableInfo.ClassName)}");
        builder.AppendLine("        {");
        builder.AppendLine($"            private const string Table = \"{Escape(tableInfo.TableCollectionName)}\";");

        var sortedEntries = tableInfo.Entries.OrderBy(entry => entry.Key).ToArray();
        var emittedMethods = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in sortedEntries)
        {
            var methodName = KeyToMethodName(entry.Key, tableInfo.TableCollectionName);

            if (!emittedMethods.Add(methodName))
                continue; // skip duplicate method names

            var xmlComment = EscapeXml(entry.EnglishText);

            builder.AppendLine();
            builder.AppendLine($"            /// <summary>{xmlComment}</summary>");
            builder.AppendLine($"            /// <remarks>Key: {EscapeXml(entry.Key)}</remarks>");

            if (entry.Args.Length == 0)
            {
                // No args
                builder.AppendLine($"            public static string {methodName}() => Loc.Get(Table, {entry.Id}L);");
            }
            else if (IsSmartArgs(entry.Args))
            {
                // Smart string args
                var paramList = string.Join(", ", entry.Args.Select(
                    arg => $"{arg.Type} {Sanitize(arg.Name)}"));
                var anonFields = string.Join(", ", entry.Args.Select(arg =>
                {
                    // If the raw placeholder equals the parameter name, use shorthand
                    return arg.RawPlaceholder == arg.Name
                        ? arg.Name
                        : $"{arg.RawPlaceholder} = {Sanitize(arg.Name)}";
                }));

                builder.AppendLine($"            public static string {methodName}({paramList})");
                builder.AppendLine($"                => Loc.Get(Table, {entry.Id}L, new {{ {anonFields} }});");
            }
            else
            {
                // Positional args
                var paramList = string.Join(", ", entry.Args.Select(
                    arg => $"{arg.Type} {arg.Name}"));
                var argList = string.Join(", ", entry.Args.Select(arg => arg.Name));

                builder.AppendLine($"            public static string {methodName}({paramList})");
                builder.AppendLine($"                => Loc.Get(Table, {entry.Id}L, {argList});");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Determines if the args represent smart string arguments (named) vs positional.
    /// Positional args are generated as "arg0", "arg1", etc. with type "object".
    /// </summary>
    private static bool IsSmartArgs(EntryArg[] args)
    {
        return args.Length > 0 && args[0].Type != "object";
    }

    /// <summary>
    /// Converts a localization key to a C# method name.
    /// Strips the table collection name prefix, then removes dots to concatenate segments.
    /// </summary>
    internal static string KeyToMethodName(string key, string tableCollectionName)
    {
        var remaining = key;

        var prefix = tableCollectionName + ".";
        if (remaining.StartsWith(prefix))
            remaining = remaining.Substring(prefix.Length);

        // Remove dots to concatenate segments
        remaining = remaining.Replace(".", "");

        return Sanitize(remaining);
    }

    private static string Sanitize(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "_";

        var builder = new StringBuilder(name.Length);
        for (var index = 0; index < name.Length; index++)
        {
            var character = name[index];
            if (index == 0 && char.IsDigit(character))
                builder.Append('_');

            if (char.IsLetterOrDigit(character) || character == '_')
                builder.Append(character);
            else
                builder.Append('_');
        }

        var result = builder.ToString();
        return IsReservedWord(result) ? "@" + result : result;
    }

    private static bool IsReservedWord(string word)
    {
        switch (word)
        {
            case "abstract": case "as": case "base": case "bool": case "break":
            case "byte": case "case": case "catch": case "char": case "checked":
            case "class": case "const": case "continue": case "decimal": case "default":
            case "delegate": case "do": case "double": case "else": case "enum":
            case "event": case "explicit": case "extern": case "false": case "finally":
            case "fixed": case "float": case "for": case "foreach": case "goto":
            case "if": case "implicit": case "in": case "int": case "interface":
            case "internal": case "is": case "lock": case "long": case "namespace":
            case "new": case "null": case "object": case "operator": case "out":
            case "override": case "params": case "private": case "protected": case "public":
            case "readonly": case "ref": case "return": case "sbyte": case "sealed":
            case "short": case "sizeof": case "stackalloc": case "static": case "string":
            case "struct": case "switch": case "this": case "throw": case "true":
            case "try": case "typeof": case "uint": case "ulong": case "unchecked":
            case "unsafe": case "ushort": case "using": case "virtual": case "void":
            case "volatile": case "while":
                return true;
            default:
                return false;
        }
    }

    private static string Escape(string text)
    {
        return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("\n", " ")
            .Replace("\r", "");
    }
}
