using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Unity.Localization.Roslyn;

[Generator]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "MedievalLocalization.Roslyn";
    private const string GeneratedClassName = "LOC";

    private static readonly string LocalizationFilePath = Path.Combine("Localization", "Data", "Tables");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            //.Where(file => Path.GetExtension(file.Path) == "asset")
            .Where(file => file.Path.Contains(LocalizationFilePath))
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private const string ClassFormat = "\t\tpublic static {0} {0} {{ get; private set; }} = new();";

    // find pairs of Xyz.asset & XzySharedData.asset
    // XyzSharedData.asset must have m_TableCollectionNameGuidString: <GUID>
    // Xyz.asset must have m_SharedData: {fileID: 11400000, guid: <GUID>, type: 2}
    // parse SharedData.asset by
    //  for each entry in m_Entries
    //      if entry has 

    private void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        var tableInfos = new List<TableInfo>();

        foreach (var file in files)
        {
            if (file is null)
                continue;

            var tableName = Path.GetFileNameWithoutExtension(file.Path).TrimEnd("_en");
            tableInfos.Add(new TableInfo(file, tableName));
        }

        var tables = string.Join("\n", tableInfos.Select(info => string.Format(ClassFormat, info.Name)));
        var tableFiles = "// " + string.Join("\n// ", tableInfos.Select(info => info.OriginalText.Path));

        var source = $$"""
                       // <auto-generated/>
                       namespace {{Namespace}}
                       {
                           public static partial class {{GeneratedClassName}}
                           {
                               {{tableFiles}}
                         
                               {{tables}}
                           }
                       }
                       """;

        foreach (var tableInfo in tableInfos)
        {
            GenerateTableClass(context, tableInfo);
        }

        // Add the source code to the compilation.
        context.AddSource($"{GeneratedClassName}.g.cs", source);
    }

    private void GenerateTableClass(SourceProductionContext context, TableInfo tableInfo)
    {
        var lines = tableInfo.OriginalText.GetText(context.CancellationToken)?.Lines;

        // Build up the source code.
        var source = $$"""
                       // <auto-generated/>

                       namespace {{Namespace}}
                       {
                           public sealed class {{tableInfo.Name}}
                           {
                               // lines: {{lines?.Count ?? 0}}
                               // strings: ???
                               // generatable strings: ???
                           }
                       }
                       """;

        context.AddSource($"{tableInfo.Name}.g.cs", source);
    }
}