using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MedievalMerchant.Generators
{
    /// <summary>
    /// Generates the C# source code for the Loc partial class with one nested class per table.
    /// </summary>
    public static class LocClassEmitter
    {
        public static string Emit(IEnumerable<TableInfo> tables)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by MedievalMerchant.Generators");
            sb.AppendLine("// Do not edit this file manually.");
            sb.AppendLine();
            sb.AppendLine("namespace Features.Localization");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Loc");
            sb.AppendLine("    {");

            var sortedTables = tables.OrderBy(t => t.TableCollectionName).ToList();
            for (int t = 0; t < sortedTables.Count; t++)
            {
                var table = sortedTables[t];
                if (string.IsNullOrEmpty(table.TableCollectionName))
                    continue;

                var className = Sanitize(table.TableCollectionName);

                sb.AppendLine($"        /// <summary>String table: {EscapeXml(table.TableCollectionName)}</summary>");
                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");
                sb.AppendLine($"            private const string T = \"{Escape(table.TableCollectionName)}\";");
                sb.AppendLine();

                var sortedEntries = table.Entries.OrderBy(e => e.Key).ToList();
                for (int i = 0; i < sortedEntries.Count; i++)
                {
                    var entry = sortedEntries[i];
                    var methodName = KeyToMethodName(entry.Key, table.TableCollectionName);

                    // XML doc comment with English text
                    if (!string.IsNullOrEmpty(entry.EnglishText))
                    {
                        sb.AppendLine($"            /// <summary>{EscapeXml(entry.EnglishText)}</summary>");
                    }

                    if (entry.ArgCount > 0)
                    {
                        // Method with params object[] args
                        sb.AppendLine($"            public static string {methodName}(params object[] args) => Get(T, {entry.Id}L, args);");
                    }
                    else
                    {
                        // Property
                        sb.AppendLine($"            public static string {methodName} => Get(T, {entry.Id}L);");
                    }

                    if (i < sortedEntries.Count - 1)
                        sb.AppendLine();
                }

                sb.AppendLine("        }");

                if (t < sortedTables.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Converts a localization key to a C# method/property name.
        /// Strips the table collection name prefix, then replaces '.' with '_'.
        /// </summary>
        internal static string KeyToMethodName(string key, string tableCollectionName)
        {
            var remaining = key;

            // Strip table name prefix (e.g., "Trade." from "Trade.NetProfit")
            var prefix = tableCollectionName + ".";
            if (remaining.StartsWith(prefix))
            {
                remaining = remaining.Substring(prefix.Length);
            }

            // Replace dots with underscores
            remaining = remaining.Replace('.', '_');

            return Sanitize(remaining);
        }

        /// <summary>
        /// Ensures the identifier is a valid C# identifier.
        /// </summary>
        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            var sb = new StringBuilder(name.Length);
            for (int i = 0; i < name.Length; i++)
            {
                var c = name[i];
                if (i == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }

            var result = sb.ToString();

            // Handle C# reserved words
            if (IsReservedWord(result))
                return "@" + result;

            return result;
        }

        private static bool IsReservedWord(string word)
        {
            switch (word)
            {
                case "abstract": case "as": case "base": case "bool": case "break":
                case "byte": case "case": case "catch": case "char": case "checked":
                case "class": case "const": case "continue": case "decimal": case "default":
                case "delegate": case "do": case "double": case "else": case "enum":
                case "event": case "explicit": case "extern": case "false": case "finally":
                case "fixed": case "float": case "for": case "foreach": case "goto":
                case "if": case "implicit": case "in": case "int": case "interface":
                case "internal": case "is": case "lock": case "long": case "namespace":
                case "new": case "null": case "object": case "operator": case "out":
                case "override": case "params": case "private": case "protected": case "public":
                case "readonly": case "ref": case "return": case "sbyte": case "sealed":
                case "short": case "sizeof": case "stackalloc": case "static": case "string":
                case "struct": case "switch": case "this": case "throw": case "true":
                case "try": case "typeof": case "uint": case "ulong": case "unchecked":
                case "unsafe": case "ushort": case "using": case "virtual": case "void":
                case "volatile": case "while":
                    return true;
                default:
                    return false;
            }
        }

        private static string Escape(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeXml(string s)
        {
            return s
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("\n", " ")
                .Replace("\r", "");
        }
    }
}
